baseURL = 'https://johnmontroy.com'
languageCode = 'en-us'
title = 'John Montroy'
author = "John Montroy"
copyright = "Copyright © 2025, John Montroy."
theme = 'hugo-bearblog'

enableRobotsTXT = true

[outputs]
  home = ['html']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[taxonomies]
  tag = "tags"

[params]
  hideMadeWithLine = true
  description = "john montroy personal website"

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  favicon = "images/favicon.png"

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  images = ["images/share.png"]

  title = "john montroy"

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
  
